name: "rtr"

autonomous_systems:
  # legit
  - asn: 1001
    routers: 2
    loopback_start: "192.168.1.1/32"
    prefix: "10.1.1.0/22"
    links:
      kind: "full-mesh"
  
  # should be blocked
  - asn: 1002
    routers: 2
    loopback_start: "192.168.2.1/32"
    prefix: "10.1.1.0/22"
    links:
      kind: "full-mesh"

  - asn: 1003
    routers: 1
    loopback_start: "192.168.3.1/32"
    prefix: "172.20.1.0/24"
    rpki:
      rpki:
      servers:
        - myRPKI

  - asn: 2001
    routers: 1
    loopback_start: "192.168.201.1/32"
    prefix: "172.20.201.0/24"


external_links:
  - from:
      asn: 1003
      router_id: 1
    to:
      asn: 1001
      router_id: 1
    rel: "p2p"
  - from:
      asn: 1003
      router_id: 1
    to:
      asn: 1002
      router_id: 1
    rel: "p2p"
  - from:
      asn: 2001
      router_id: 1
    to:
      asn: 1003
      router_id: 1
    rel: "p2p"

rpki:
  myRPKI:
    linked_to:
      asn: 2001
      router_id: 1
    cache_file: rpki.json