name: "isis"

autonomous_systems:
  - asn: 10
    routers: 5
    loopback_start: "10.1.1.1/32"
    # prefix: "2001:abcd::1/64"
    prefix: "192.168.1.1/24"
    igp: "ospf"
    bgp:
      disabled: true
    ospf:
      areas:
        0: [1, 2]
        1: [3, 4]
        2: [5]
      stubs: [1, 2]
    links:
      kind: 'manual'
      subnet_length: 30
      file: internal-links
    
